"""Canonical concept vocabulary for the inequality-mobility domain."""

CANONICAL_CONCEPTS: tuple = (
    "economic inequality",
    "income inequality",
    "wealth inequality",
    "intergenerational mobility",
    "social mobility",
    "educational inequality",
    "educational attainment",
    "residential segregation",
    "neighborhood effects",
    "social capital",
    "wealth concentration",
    "capital accumulation",
    "labor market segmentation",
    "political institutions",
    "redistribution",
    "public education",
    "school quality",
    "parental income",
    "child earnings",
    "earnings elasticity",
    "gini coefficient",
    "great gatsby curve",
    "opportunity",
    "upward mobility",
    "downward mobility",
    "poverty",
    "affluence",
    "elite universities",
    "private schooling",
    "tutoring",
    "school funding",
    "property taxes",
    "racial segregation",
    "professional networks",
    "recommendation letters",
    "hiring",
    "credential barriers",
    "vocational training",
    "informal labor markets",
    "minimum wage",
    "labor protections",
    "taxation of capital",
    "public investment",
    "healthcare access",
    "early childhood",
    "college completion",
    "earnings",
    "wealth transfers",
    "inheritance",
    "other",
)

CONCEPT_CATEGORIES: dict = {
    "inequality": (
        "economic inequality",
        "income inequality",
        "wealth inequality",
        "gini coefficient",
        "poverty",
        "affluence",
    ),
    "mobility": (
        "intergenerational mobility",
        "social mobility",
        "upward mobility",
        "downward mobility",
        "opportunity",
        "great gatsby curve",
        "earnings elasticity",
        "child earnings",
        "parental income",
    ),
    "mechanisms": (
        "educational inequality",
        "educational attainment",
        "residential segregation",
        "neighborhood effects",
        "social capital",
        "wealth concentration",
        "capital accumulation",
        "labor market segmentation",
        "political institutions",
    ),
    "education": (
        "public education",
        "school quality",
        "elite universities",
        "private schooling",
        "tutoring",
        "school funding",
        "property taxes",
        "early childhood",
        "college completion",
    ),
    "labor": (
        "professional networks",
        "recommendation letters",
        "hiring",
        "credential barriers",
        "vocational training",
        "informal labor markets",
        "minimum wage",
        "labor protections",
        "earnings",
    ),
    "policy": (
        "redistribution",
        "taxation of capital",
        "public investment",
        "healthcare access",
        "racial segregation",
        "wealth transfers",
        "inheritance",
    ),
}
